import {
  AwsIcon,
  BlenderIcon,
  BootstrapIcon,
  ChakraUiIcon,
  CssIcon,
  DaVinciIcon,
  ExpressIcon,
  FigmaIcon,
  GitIcon,
  GitLabIcon,
  GithubIcon,
  GraphQLIcon,
  HerokuIcon,
  HtmlIcon,
  InsomniaIcon,
  InteliJComponent,
  JavaIcon,
  JestIcon,
  JsIcon,
  MaterialUiIcon,
  MongoDbIcon,
  MongooseIcon,
  MySqlIcon,
  NetlifyIcon,
  NextJsIcon,
  NodeJsIcon,
  NotionIcon,
  PhotoshopIcon,
  PhpIcon,
  PostgreSqlIcon,
  PostmanIcon,
  ReactIcon,
  ReduxIcon,
  ScrumIcon,
  SeoIcon,
  SequelizeIcon,
  SpringBootIcon,
  TailwindIcon,
  TypeScriptIcon,
  VercelIcon,
  VscIcon,
  WebpackIcon,
} from '@/components/Icons';

// Stable string keys that content data can reference instead of embedding JSX.
// Keys map 1:1 to the icon components that were previously imported directly
// into src/data/*.js content files.
export const iconMap = {
  javascript: JsIcon,
  react: ReactIcon,
  nextjs: NextJsIcon,
  redux: ReduxIcon,
  tailwind: TailwindIcon,
  chakraui: ChakraUiIcon,
  materialui: MaterialUiIcon,
  bootstrap: BootstrapIcon,
  typescript: TypeScriptIcon,
  html: HtmlIcon,
  css: CssIcon,
  postgresql: PostgreSqlIcon,
  mongodb: MongoDbIcon,
  mysql: MySqlIcon,
  nodejs: NodeJsIcon,
  sequelize: SequelizeIcon,
  mongoose: MongooseIcon,
  express: ExpressIcon,
  graphql: GraphQLIcon,
  php: PhpIcon,
  java: JavaIcon,
  springboot: SpringBootIcon,
  git: GitIcon,
  github: GithubIcon,
  gitlab: GitLabIcon,
  heroku: HerokuIcon,
  vercel: VercelIcon,
  netlify: NetlifyIcon,
  aws: AwsIcon,
  vscode: VscIcon,
  postman: PostmanIcon,
  insomnia: InsomniaIcon,
  webpack: WebpackIcon,
  jest: JestIcon,
  scrum: ScrumIcon,
  seo: SeoIcon,
  intellij: InteliJComponent,
  figma: FigmaIcon,
  notion: NotionIcon,
  photoshop: PhotoshopIcon,
  davinci: DaVinciIcon,
  blender: BlenderIcon,
};

export const resolveIcon = (name) => (name ? iconMap[name] ?? null : null);
