import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profileimg from "../../public/images/profile/yo1.3sf.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center'>
            <div className='w-1/2'>
              <Image src={profileimg} alt="vontrauwitz" className='w-[70%] h-auto mb-20' />
            </div>
            <div className='w-1/2 flex flex-col items-start self-center'>
              <AnimatedText text="Code Artist: Turning Dreams into Digital Realities." className='!text-4xl !text-left' />
              <p
                className='my-4 text-base front-medium'
              >
                Hello there! I&apos;m a highly skilled full-stack developer passionate about transforming ideas into impressive web applications. Dive into my latest projects, showcasing my programming expertise and web development. Let&apos;s embark on an exciting journey where innovation meets coding excellence.;
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link
                  href="/cvhanstrauwitzbrita.pdf"
                  target={"_blank"}
                  className='flex items-center bg-dark text-light p-1.5 px-6 rounded-lg text-lg font-semibold 
                  hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-black'
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />

                </Link>
                {/* //TODO NO ME GUSTA ESTO */}
                <Link
                  href="mailto:hans.trauwitz@gmail.com"
                  target={"_blank"}
                  className="ml-6 text-lg font-medium capitalize text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
