import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profileimg from "../../public/images/profile/yo1.3sf.png"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full '>
        <Layout>
          <div className="flex items-center justify-between w-full ">
            <div className='w-1/2'>
              <Image src={profileimg} alt="vontrauwitz" className='w-256 h-auto' />
            </div>
            <div className='w-1/2'>
              <h1>Unleashing the Power of Code to Transform Dreams into Digital Realities.</h1>
              <p>
                &apos;Hello there! I&apos;m a highly skilled full-stack developer passionate about transforming ideas into impressive web applications. Dive into my latest projects, showcasing my programming expertise and web development. Let&apos;s embark on an exciting journey where innovation meets coding excellence.&apos;
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}


